app = "portfolio-website"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "nginx:alpine"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
